# Generated by Django 4.2.1 on 2023-12-27 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_blockchaincode_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CourseID', models.AutoField(primary_key=True, serialize=False)),
                ('CourseName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DegreeProgram',
            fields=[
                ('DegreeProgramID', models.AutoField(primary_key=True, serialize=False)),
                ('DegreeProgramName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('QuestionID', models.AutoField(primary_key=True, serialize=False)),
                ('QuestionText', models.TextField()),
                ('Option1', models.CharField(max_length=255)),
                ('Option2', models.CharField(max_length=255)),
                ('Option3', models.CharField(max_length=255)),
                ('Option4', models.CharField(max_length=255)),
                ('CorrectOption', models.CharField(max_length=255)),
                ('DifficultyLevel', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Difficult', 'Difficult')], max_length=10)),
                ('Weightage', models.IntegerField()),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
            ],
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='election',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='blockchain_code',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='election',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='voter',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='user',
        ),
        migrations.DeleteModel(
            name='BlockchainCode',
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.DeleteModel(
            name='Election',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.DeleteModel(
            name='Voter',
        ),
        migrations.AddField(
            model_name='course',
            name='DegreeProgramID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.degreeprogram'),
        ),
    ]
