# Generated by Django 4.2.1 on 2023-12-27 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_course_degreeprogram_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('DegreeProgramID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.degreeprogram')),
            ],
        ),
    ]
