# Generated by Django 4.2.1 on 2023-12-27 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedPaper',
            fields=[
                ('PaperID', models.AutoField(primary_key=True, serialize=False)),
                ('DifficultyLevel', models.CharField(max_length=10)),
                ('PaperFile', models.FileField(upload_to='submitted_papers/')),
                ('Status', models.CharField(choices=[('Submitted', 'Submitted'), ('Graded', 'Graded')], default='Submitted', max_length=10)),
                ('Marks', models.IntegerField(blank=True, null=True)),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
        ),
    ]
