# Generated by Django 4.2.1 on 2023-12-27 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_submittedpaper_studentid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubmittedPaper',
        ),
    ]
