# Generated by Django 4.2.1 on 2023-12-27 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_delete_submittedpaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperSubmission',
            fields=[
                ('SubmissionID', models.AutoField(primary_key=True, serialize=False)),
                ('DifficultyLevel', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Difficult', 'Difficult')], max_length=10)),
                ('File', models.FileField(upload_to='paper_submissions/')),
                ('Status', models.CharField(choices=[('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Submitted', max_length=10)),
                ('Marks', models.IntegerField(blank=True, null=True)),
                ('Grade', models.CharField(blank=True, max_length=10, null=True)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
        ),
    ]
