# Generated by Django 4.2.1 on 2023-12-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_papersubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papersubmission',
            name='Status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Marked', 'Marked')], default='Submitted', max_length=10),
        ),
    ]
