# Generated by Django 4.2.1 on 2024-01-26 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_papersubmission_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('TeacherID', models.AutoField(primary_key=True, serialize=False)),
                ('TeacherName', models.CharField(max_length=255)),
                ('Education', models.CharField(max_length=255)),
                ('ContactNumber', models.CharField(max_length=20)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='Teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.teacher'),
        ),
    ]
