# Generated by Django 4.2.1 on 2024-01-26 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_course_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Teacher',
        ),
    ]
