# Generated by Django 4.2.1 on 2024-01-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_delete_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('TeacherID', models.AutoField(primary_key=True, serialize=False)),
                ('TeacherName', models.CharField(max_length=255)),
                ('Education', models.CharField(max_length=255)),
                ('ContactNumber', models.CharField(max_length=20)),
                ('Description', models.TextField()),
            ],
        ),
    ]
