# Generated by Django 4.2.1 on 2024-01-26 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.teacher'),
        ),
    ]
